version: "3.8"

services:
  pgdb:
    container_name: pgdb_jobsearch
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
